Create tenantConfigNewIA.json
WASdev/sample.voice.gateway pull request #262
Opened 2023-09-01 19:58 UTC by GailMarieDB

Template tenantConfig file to show how environment id and bearerToken information is passed for Watson Assistant New Experience (aka New IA) deployments on CP4D.

2023-09-01 20:12 UTC, leuvataral approved these changes

2023-09-01 20:15 UTC, jfmartinez approved these changes

2023-09-01 20:16 UTC, jfmartinez commented
@jakub-pomykala can you review this PR?

2023-09-06 10:30 UTC, jakub-pomykala requested changes
LGTM

2023-09-06 10:30 UTC, jakub-pomykala approved these changes
LGTM

2023-09-07 08:01 UTC, merged